# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: word_game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='word_game.proto',
  package='app',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10word_game2.proto\x12\x03\x61pp\"I\n\x11\x43reateGameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08gameType\x18\x02 \x01(\t\x12\x10\n\x08gameMode\x18\x03 \x01(\t\"6\n\x12\x43reateGameResponse\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12\x10\n\x08joinCode\x18\x02 \x01(\t\"5\n\x0fJoinGameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08joinCode\x18\x02 \x01(\t\"8\n\x10JoinGameResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\x12\x0e\n\x06gameId\x18\x02 \x01(\t\"!\n\x0fInitGameRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\"(\n\x10InitGameResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\"#\n\x11GetPangramRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\"%\n\x12GetPangramResponse\x12\x0f\n\x07letters\x18\x01 \x01(\t\"G\n\x15WordSubmissionRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04word\x18\x03 \x01(\t\"G\n\x16WordSubmissionResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"#\n\x11GameStatusRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\"(\n\x12GameStatusResponse\x12\x12\n\nstatusInfo\x18\x01 \x01(\t\" \n\x0e\x45ndGameRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\"\'\n\x0f\x45ndGameResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\x32\xc9\x03\n\x08WordGame\x12?\n\nCreateGame\x12\x16.app.CreateGameRequest\x1a\x17.app.CreateGameResponse\"\x00\x12\x39\n\x08JoinGame\x12\x14.app.JoinGameRequest\x1a\x15.app.JoinGameResponse\"\x00\x12\x39\n\x08InitGame\x12\x14.app.InitGameRequest\x1a\x15.app.InitGameResponse\"\x00\x12?\n\nGetPangram\x12\x16.app.GetPangramRequest\x1a\x17.app.GetPangramResponse\"\x00\x12G\n\nSubmitWord\x12\x1a.app.WordSubmissionRequest\x1a\x1b.app.WordSubmissionResponse\"\x00\x12\x44\n\x0fQueryGameStatus\x12\x16.app.GameStatusRequest\x1a\x17.app.GameStatusResponse\"\x00\x12\x36\n\x07\x45ndGame\x12\x13.app.EndGameRequest\x1a\x14.app.EndGameResponse\"\x00\x62\x06proto3'
)




_CREATEGAMEREQUEST = _descriptor.Descriptor(
  name='CreateGameRequest',
  full_name='app.CreateGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='app.CreateGameRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameType', full_name='app.CreateGameRequest.gameType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameMode', full_name='app.CreateGameRequest.gameMode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=98,
)


_CREATEGAMERESPONSE = _descriptor.Descriptor(
  name='CreateGameResponse',
  full_name='app.CreateGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.CreateGameResponse.gameId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joinCode', full_name='app.CreateGameResponse.joinCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=154,
)


_JOINGAMEREQUEST = _descriptor.Descriptor(
  name='JoinGameRequest',
  full_name='app.JoinGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='app.JoinGameRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joinCode', full_name='app.JoinGameRequest.joinCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=209,
)


_JOINGAMERESPONSE = _descriptor.Descriptor(
  name='JoinGameResponse',
  full_name='app.JoinGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='app.JoinGameResponse.responseCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.JoinGameResponse.gameId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=267,
)


_INITGAMEREQUEST = _descriptor.Descriptor(
  name='InitGameRequest',
  full_name='app.InitGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.InitGameRequest.gameId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=302,
)


_INITGAMERESPONSE = _descriptor.Descriptor(
  name='InitGameResponse',
  full_name='app.InitGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='app.InitGameResponse.responseCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=344,
)


_GETPANGRAMREQUEST = _descriptor.Descriptor(
  name='GetPangramRequest',
  full_name='app.GetPangramRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.GetPangramRequest.gameId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=381,
)


_GETPANGRAMRESPONSE = _descriptor.Descriptor(
  name='GetPangramResponse',
  full_name='app.GetPangramResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='letters', full_name='app.GetPangramResponse.letters', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=420,
)


_WORDSUBMISSIONREQUEST = _descriptor.Descriptor(
  name='WordSubmissionRequest',
  full_name='app.WordSubmissionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.WordSubmissionRequest.gameId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='app.WordSubmissionRequest.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='word', full_name='app.WordSubmissionRequest.word', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=493,
)


_WORDSUBMISSIONRESPONSE = _descriptor.Descriptor(
  name='WordSubmissionResponse',
  full_name='app.WordSubmissionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='app.WordSubmissionResponse.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='app.WordSubmissionResponse.total', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='app.WordSubmissionResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=566,
)


_GAMESTATUSREQUEST = _descriptor.Descriptor(
  name='GameStatusRequest',
  full_name='app.GameStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.GameStatusRequest.gameId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=568,
  serialized_end=603,
)


_GAMESTATUSRESPONSE = _descriptor.Descriptor(
  name='GameStatusResponse',
  full_name='app.GameStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusInfo', full_name='app.GameStatusResponse.statusInfo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=645,
)


_ENDGAMEREQUEST = _descriptor.Descriptor(
  name='EndGameRequest',
  full_name='app.EndGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.EndGameRequest.gameId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=679,
)


_ENDGAMERESPONSE = _descriptor.Descriptor(
  name='EndGameResponse',
  full_name='app.EndGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='app.EndGameResponse.responseCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=681,
  serialized_end=720,
)

DESCRIPTOR.message_types_by_name['CreateGameRequest'] = _CREATEGAMEREQUEST
DESCRIPTOR.message_types_by_name['CreateGameResponse'] = _CREATEGAMERESPONSE
DESCRIPTOR.message_types_by_name['JoinGameRequest'] = _JOINGAMEREQUEST
DESCRIPTOR.message_types_by_name['JoinGameResponse'] = _JOINGAMERESPONSE
DESCRIPTOR.message_types_by_name['InitGameRequest'] = _INITGAMEREQUEST
DESCRIPTOR.message_types_by_name['InitGameResponse'] = _INITGAMERESPONSE
DESCRIPTOR.message_types_by_name['GetPangramRequest'] = _GETPANGRAMREQUEST
DESCRIPTOR.message_types_by_name['GetPangramResponse'] = _GETPANGRAMRESPONSE
DESCRIPTOR.message_types_by_name['WordSubmissionRequest'] = _WORDSUBMISSIONREQUEST
DESCRIPTOR.message_types_by_name['WordSubmissionResponse'] = _WORDSUBMISSIONRESPONSE
DESCRIPTOR.message_types_by_name['GameStatusRequest'] = _GAMESTATUSREQUEST
DESCRIPTOR.message_types_by_name['GameStatusResponse'] = _GAMESTATUSRESPONSE
DESCRIPTOR.message_types_by_name['EndGameRequest'] = _ENDGAMEREQUEST
DESCRIPTOR.message_types_by_name['EndGameResponse'] = _ENDGAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateGameRequest = _reflection.GeneratedProtocolMessageType('CreateGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMEREQUEST,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.CreateGameRequest)
  })
_sym_db.RegisterMessage(CreateGameRequest)

CreateGameResponse = _reflection.GeneratedProtocolMessageType('CreateGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMERESPONSE,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.CreateGameResponse)
  })
_sym_db.RegisterMessage(CreateGameResponse)

JoinGameRequest = _reflection.GeneratedProtocolMessageType('JoinGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINGAMEREQUEST,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.JoinGameRequest)
  })
_sym_db.RegisterMessage(JoinGameRequest)

JoinGameResponse = _reflection.GeneratedProtocolMessageType('JoinGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _JOINGAMERESPONSE,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.JoinGameResponse)
  })
_sym_db.RegisterMessage(JoinGameResponse)

InitGameRequest = _reflection.GeneratedProtocolMessageType('InitGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITGAMEREQUEST,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.InitGameRequest)
  })
_sym_db.RegisterMessage(InitGameRequest)

InitGameResponse = _reflection.GeneratedProtocolMessageType('InitGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _INITGAMERESPONSE,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.InitGameResponse)
  })
_sym_db.RegisterMessage(InitGameResponse)

GetPangramRequest = _reflection.GeneratedProtocolMessageType('GetPangramRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPANGRAMREQUEST,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.GetPangramRequest)
  })
_sym_db.RegisterMessage(GetPangramRequest)

GetPangramResponse = _reflection.GeneratedProtocolMessageType('GetPangramResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPANGRAMRESPONSE,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.GetPangramResponse)
  })
_sym_db.RegisterMessage(GetPangramResponse)

WordSubmissionRequest = _reflection.GeneratedProtocolMessageType('WordSubmissionRequest', (_message.Message,), {
  'DESCRIPTOR' : _WORDSUBMISSIONREQUEST,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.WordSubmissionRequest)
  })
_sym_db.RegisterMessage(WordSubmissionRequest)

WordSubmissionResponse = _reflection.GeneratedProtocolMessageType('WordSubmissionResponse', (_message.Message,), {
  'DESCRIPTOR' : _WORDSUBMISSIONRESPONSE,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.WordSubmissionResponse)
  })
_sym_db.RegisterMessage(WordSubmissionResponse)

GameStatusRequest = _reflection.GeneratedProtocolMessageType('GameStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATUSREQUEST,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.GameStatusRequest)
  })
_sym_db.RegisterMessage(GameStatusRequest)

GameStatusResponse = _reflection.GeneratedProtocolMessageType('GameStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATUSRESPONSE,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.GameStatusResponse)
  })
_sym_db.RegisterMessage(GameStatusResponse)

EndGameRequest = _reflection.GeneratedProtocolMessageType('EndGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDGAMEREQUEST,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.EndGameRequest)
  })
_sym_db.RegisterMessage(EndGameRequest)

EndGameResponse = _reflection.GeneratedProtocolMessageType('EndGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENDGAMERESPONSE,
  '__module__' : 'word_game2_pb2'
  # @@protoc_insertion_point(class_scope:app.EndGameResponse)
  })
_sym_db.RegisterMessage(EndGameResponse)



_WORDGAME = _descriptor.ServiceDescriptor(
  name='WordGame',
  full_name='app.WordGame',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=723,
  serialized_end=1180,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateGame',
    full_name='app.WordGame.CreateGame',
    index=0,
    containing_service=None,
    input_type=_CREATEGAMEREQUEST,
    output_type=_CREATEGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='JoinGame',
    full_name='app.WordGame.JoinGame',
    index=1,
    containing_service=None,
    input_type=_JOINGAMEREQUEST,
    output_type=_JOINGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InitGame',
    full_name='app.WordGame.InitGame',
    index=2,
    containing_service=None,
    input_type=_INITGAMEREQUEST,
    output_type=_INITGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPangram',
    full_name='app.WordGame.GetPangram',
    index=3,
    containing_service=None,
    input_type=_GETPANGRAMREQUEST,
    output_type=_GETPANGRAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitWord',
    full_name='app.WordGame.SubmitWord',
    index=4,
    containing_service=None,
    input_type=_WORDSUBMISSIONREQUEST,
    output_type=_WORDSUBMISSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryGameStatus',
    full_name='app.WordGame.QueryGameStatus',
    index=5,
    containing_service=None,
    input_type=_GAMESTATUSREQUEST,
    output_type=_GAMESTATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndGame',
    full_name='app.WordGame.EndGame',
    index=6,
    containing_service=None,
    input_type=_ENDGAMEREQUEST,
    output_type=_ENDGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORDGAME)

DESCRIPTOR.services_by_name['WordGame'] = _WORDGAME

# @@protoc_insertion_point(module_scope)
